version: '3.8'

services:
  app:
    container_name: crematory_app
    build:
      context: ./php
      dockerfile: php.DockerFile
#    working_dir: /var/www
    volumes:
      - ../backend/:/var/www/laravel
#    networks:
#      - nw
    restart: unless-stopped

  db:
    container_name: crematory_db
    image: 'postgres:18-alpine'
    restart: unless-stopped
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - postgres_net

  pgadmin:
    container_name: crematory_pgadmin
    image: 'dpage/pgadmin4:9.8'
    env_file:
      - pgadmin.env
    restart: no
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres_net


volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgres_net:
    driver: bridge