#version: '3.8'

services:
  db:
    container_name: crem_db
    restart: no
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespasswordlaravel"

    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - crem_net

  back:
    container_name: crem_back
    build:
      context: ..
      dockerfile: deploy/php/php.DockerFile
    volumes:
      - ../backend/:/var/www/backend
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - crem_net


  pgadmin:
    container_name: crem_pgadmin
    image: 'dpage/pgadmin4:9.8'
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgrespasswordlaravel"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
    env_file:
      - pgadmin.env
    restart: no
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - crem_net

  web:
    container_name: crem_web
    image: 'nginx:stable-alpine'
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/:/var/www/frontend
      - ../backend/:/var/www/backend
    depends_on:
      - db
      - back
      - front
    networks:
      - crem_net

  front:
    container_name: crem_front
    build:
      context: ..
      dockerfile: deploy/proxy/proxy.DockerFile
    volumes:
      - ../frontend/:/var/www/frontend
      - /var/www/frontend/node_modules
    depends_on:
      - db
      - back
    networks:
      - crem_net


volumes:
  postgres-data:
  pgadmin-data:

networks:
  crem_net:
    driver: bridge
