#version: '3.8'

services:
  app:
    container_name: crematory_app
    build:
      context: ./php
      dockerfile: php.DockerFile
#    working_dir: /var/www
    volumes:
      - ../backend/:/var/www/laravel
    networks:
      - postgres_net
    restart: unless-stopped
#    ports:
#    - "8000:8000"

  db:
    container_name: crematory_db
    image: 'postgres:latest'
    restart: no
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data"
#    ports:
#      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - postgres_net

  pgadmin:
    container_name: crematory_pgadmin
    image: 'dpage/pgadmin4:9.8'
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgrespasswordlaravel"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    restart: no
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres_net


volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgres_net:
    driver: bridge