#version: '3.8'

services:
  back:
    container_name: crem_back
    build:
      context: ./php
      dockerfile: php.DockerFile
    volumes:
      - ../backend/:/var/www/laravel
    networks:
      - crem_net
    restart: unless-stopped
    depends_on:
      - db
    command: bash -c "composer install && php artisan key:generate && php artisan migrate && tail -F /dev/null"
#    command: tail -F /dev/null

  db:
    container_name: crem_db
    image: 'postgres:17-alpine'
    restart: no
    user: postgres
    build:
      context: postgres
      dockerfile: postgres.DockerFile
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespasswordlaravel"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - crem_net

  pgadmin:
    container_name: crem_pgadmin
    image: 'dpage/pgadmin4:9.8'
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgrespasswordlaravel"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
    restart: no
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - crem_net

  web:
    container_name: crem_web
    image: 'nginx:stable-alpine'
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../backend/:/var/www/laravel
      - ../frontend/:/var/www/front
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
      - back
      - front
    networks:
      - crem_net

  front:
    container_name: crem_front
    build:
      context: ./proxy
      dockerfile: proxy.DockerFile
#    image: 'node:25-alpine3.21'
    volumes:
      - ../frontend/:/var/www/front
    depends_on:
      - db
      - back
    networks:
      - crem_net
    command: bash -c "npm install && npm run dev && tail -F /dev/null"



volumes:
  postgres-data:
  pgadmin-data:

networks:
  crem_net:
    driver: bridge