#version: '3.8'

services:
  back:
    container_name: crematory_app
    build:
      context: ./php
      dockerfile: php.DockerFile
    volumes:
      - ../backend/:/var/www/laravel
    networks:
      - crematory_net
    restart: unless-stopped
    depends_on:
      - db
#    command: bash -c "composer install && php artisan key:generate && php artisan migrate"
#    command: tail -F

  db:
    container_name: crematory_db
    image: 'postgres:17-alpine'
    restart: no
    user: postgres
    build:
      context: postgres
      dockerfile: postgres.DockerFile
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespasswordlaravel"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - crematory_net

  pgadmin:
    container_name: crematory_pgadmin
    image: 'dpage/pgadmin4:9.8'
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgrespasswordlaravel"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
    restart: no
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - crematory_net

  web:
    container_name: crematory_web
    image: 'nginx:stable-alpine'
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../backend/:/var/www/laravel
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
      - back
    networks:
      - crematory_net

#  front:
#    container_name: front

volumes:
  postgres-data:
  pgadmin-data:

networks:
  crematory_net:
    driver: bridge